services:
  news-recommender:
    build: .
    container_name: news-recommender-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    volumes:
      - ./Dataset:/app/Dataset:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - news-recommender-network

networks:
  news-recommender-network:
    driver: bridge
